"""
core/cognition_core/interfaces.py — FRIDAY 6.0 (M13)
Persistence abstractions. Cognition must never couple directly to SQLite — the
registry/resolver/belief system depend only on these Protocols, and concrete
backends (SQLite, in-memory) are injected. This keeps storage swappable and the
cognitive logic testable without a database.
"""

from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from .models import Belief, Entity


@runtime_checkable
class EntityRepository(Protocol):
    """Persistence for entities + their name aliases. Implementations own all I/O."""

    def allocate_id(self) -> str: ...
    def add(self, entity: Entity) -> None: ...
    def get(self, stable_id: str) -> Optional[Entity]: ...
    def update(self, entity: Entity) -> None: ...
    def remove(self, stable_id: str) -> None: ...
    def all(self) -> list[Entity]: ...
    def by_kind(self, kind: str) -> list[Entity]: ...
    def find_by_label(self, kind: str, label: str) -> Optional[Entity]: ...

    # aliases (normalized text → stable id)
    def add_alias(self, normalized: str, stable_id: str, kind: str) -> None: ...
    def resolve_alias(self, normalized: str, kind: Optional[str] = None) -> Optional[str]: ...
    def aliases_for(self, stable_id: str) -> list[str]: ...

    def counts(self) -> dict: ...
    def close(self) -> None: ...


@runtime_checkable
class BeliefRepository(Protocol):
    """Persistence for beliefs. Implementations own all I/O."""

    def add(self, belief: Belief) -> None: ...
    def get(self, belief_id: str) -> Optional[Belief]: ...
    def update(self, belief: Belief) -> None: ...
    def find(self, *, subject: Optional[str] = None, predicate: Optional[str] = None,
             status: Optional[str] = None) -> list[Belief]: ...
    def all(self) -> list[Belief]: ...
    def counts(self) -> dict: ...
    def close(self) -> None: ...
