"""
core/audio/cognition/config.py — FRIDAY V3 (M15)
Configuration for Auditory Cognition. Typed, serializable, injectable — no tunable is
hardcoded inside a module. Mirrors the milestone's YAML surface:

    audio:
      wake_word: friday
      continuous_listening: true
      wake_confidence: 0.85
      noise_filter: true
      audio_event_detection: true
      store_audio_events: true

`AudioCognitionConfig.from_dict` is tolerant: unknown keys are ignored and missing
sections fall back to defaults, so a slice of friday_config.json can be passed directly.
No I/O, no global state, side-effect-free.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Optional

_ROOT = Path(__file__).resolve().parents[3]


@dataclass
class WakeConfig:
    wake_word: str = "friday"
    extra_words: list = field(default_factory=list)
    wake_confidence: float = 0.85            # confidence-based wake detection
    cooldown_s: float = 2.0                  # ignore repeat triggers within this window
    self_speech_guard_s: float = 0.5         # extra suppression after TTS finishes
    resume_after_speaking: bool = True       # auto-resume listening once TTS ends


@dataclass
class SpeechConfig:
    continuous_listening: bool = True
    noise_filter: bool = True
    dedup_window_s: float = 4.0              # suppress identical transcripts within this window
    dedup_similarity: float = 0.92          # similarity above which two transcripts are "the same"
    min_partial_chars: int = 2              # shortest transcript treated as a real partial


@dataclass
class EventDetectionConfig:
    enabled: bool = True
    window_s: float = 0.6                    # analysis window for environmental sounds
    hop_s: float = 0.3                       # how often the window is re-analyzed
    min_confidence: float = 0.55             # detection threshold
    per_type_cooldown_s: float = 1.5         # debounce repeated detections of the same sound
    # sounds that are always-significant (override the memory significance gate)
    emergency_sounds: list = field(default_factory=lambda: [
        "glass_breaking", "alarm", "crying"])
    disabled_sounds: list = field(default_factory=list)   # opt out specific detectors


@dataclass
class MemoryConfig:
    store_audio_events: bool = True
    db_path: Optional[str] = None            # default: data/auditory_memory.db
    significance_threshold: float = 0.6      # only meaningful events persist
    persistent: bool = True
    max_session_events: int = 5000


@dataclass
class AttentionConfig:
    # priority bands (higher = more salient): emergency > wake > speech > environmental > background
    emergency: float = 1.0
    wake_word: float = 0.85
    speech: float = 0.7
    environmental: float = 0.45
    background: float = 0.1
    dynamic: bool = True                     # let recent activity nudge priorities


@dataclass
class AudioCognitionConfig:
    wake: WakeConfig = field(default_factory=WakeConfig)
    speech: SpeechConfig = field(default_factory=SpeechConfig)
    events: EventDetectionConfig = field(default_factory=EventDetectionConfig)
    memory: MemoryConfig = field(default_factory=MemoryConfig)
    attention: AttentionConfig = field(default_factory=AttentionConfig)
    session_id: str = ""                     # set per run; "" → auto-generated by the service

    def to_dict(self) -> dict:
        return asdict(self)

    @staticmethod
    def from_dict(d: Optional[dict]) -> "AudioCognitionConfig":
        d = dict(d or {})
        # allow a flat "audio:" block (the milestone's example) as well as nested sections
        flat = {k: d[k] for k in (
            "wake_word", "continuous_listening", "wake_confidence", "noise_filter",
            "audio_event_detection", "store_audio_events") if k in d}
        cfg = AudioCognitionConfig()
        if "wake_word" in flat:
            cfg.wake.wake_word = flat["wake_word"]
        if "wake_confidence" in flat:
            cfg.wake.wake_confidence = float(flat["wake_confidence"])
        if "continuous_listening" in flat:
            cfg.speech.continuous_listening = bool(flat["continuous_listening"])
        if "noise_filter" in flat:
            cfg.speech.noise_filter = bool(flat["noise_filter"])
        if "audio_event_detection" in flat:
            cfg.events.enabled = bool(flat["audio_event_detection"])
        if "store_audio_events" in flat:
            cfg.memory.store_audio_events = bool(flat["store_audio_events"])
        # nested sections (full control)
        for section, klass in (("wake", WakeConfig), ("speech", SpeechConfig),
                               ("events", EventDetectionConfig), ("memory", MemoryConfig),
                               ("attention", AttentionConfig)):
            sub = d.get(section)
            if isinstance(sub, dict):
                current = asdict(getattr(cfg, section))
                current.update({k: v for k, v in sub.items() if k in current})
                setattr(cfg, section, klass(**current))
        if isinstance(d.get("session_id"), str):
            cfg.session_id = d["session_id"]
        return cfg

    def auditory_memory_path(self) -> str:
        return self.memory.db_path or str(_ROOT / "data" / "auditory_memory.db")
